### PR TITLE
Changed the call to inspect.getargspec() to call inspect.signature() …

### PR DESCRIPTION
**Pull request by TarisMarh**
…because the getargspec() function was removed from the inspect module.

Without this, the library does not work with Python 3.11.

### CODE REVIEW

**Comment by hemmouda** [comment]
This pr would also fix #21 that gives this error:
`TypeError: secret() missing 1 required positional argument: 'db'`
